name: 'SYSU Health Report'
description: 'Automatic health report for SYSU'
author: 'Editio'

branding:
  icon: thermometer
  color: green

runs:
  using: "composite"
  steps:
    - shell: powershell
      env:
        PYTHONIOENCODING: utf-8
        PYTHONLEGACYWINDOWSSTDIO: utf-8
      run: |
        pip install -r ${{ github.action_path }}\requirements.txt
        Set-TimeZone -Name "China Standard Time"
        python ${{ github.action_path }}\healthApply.py
