name: health report

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 22,1 * * *'
  workflow_dispatch:

jobs:
  report:
    runs-on: windows-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Health Report
        uses: djh29/sysu_health@main
      
